config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
   resources :restaurants
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  # Route for destroying a restaurant
  delete 'restaurants/:id', to: 'restaurants#destroy', as: 'destroy_restaurant'
end

Rails.application.routes.draw do

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
# app/models/restaurant.rb

class Restaurant < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: %w(Indian Italian Japanese Mexican American),
                                                    message: "%{value} is not a valid category" }

  # Associations
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  before_action :set_review, only: [:show, :destroy]

  # GET /restaurants/1/reviews/new
  def new
    @review = @restaurant.reviews.build
  end

  # POST /restaurants/1/reviews
  def create
    @review = @restaurant.reviews.build(review_params)

    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  # DELETE /restaurants/1/reviews/1
  def destroy
    @review.destroy
    redirect_to @restaurant, notice: 'Review was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def set_review
      @review = @restaurant.reviews.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :aphone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= form_with model: @restaurant, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :address %>
  <%= form.text_field :address %>

  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>

  <%= form.label :category %>
  <%= form.text_field :category %>

  <%= form.submit 'Update Restaurant' %>
<% end %>

<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.category %></td>
        <td>
          <%= link_to 'Edit', edit_restaurant_path(restaurant) %> |
          <%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= form_with model: @restaurant, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :address %>
  <%= form.text_field :address %>

  <%= form.label :phone_number %>
  <%= form.text_field :phone_number %>

  <%= form.label :category %>
  <%= form.text_field :category %>

  <%= form.submit 'Create Restaurant' %>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Address:</strong> <%= @restaurant.address %></p>
<p><strong>Phone Number:</strong> <%= @restaurant.phone_number %></p>
<p><strong>Category:</strong> <%= @restaurant.category %></p>

<%= link_to 'Back', restaurants_path %>